spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weifu?useUnicode=true&characterEncoding=utf8&serverTimezone=JST
    username: teieigun
    password: duezwi4r
    driverClassName: com.mysql.jdbc.Driver

server:  
  tomcat:
    max-http-post-size: 10000000